### ISSUE TITLE
BUG: itkGrayscaleImageSegmentationVolumeEstimatorTest1 test fails

### ISSUE THREAD

**Issue by mseng10** [InsightSoftwareConsortium/LesionSizingToolkit#38]
When LesionSizingToolkit is compiled against any version of ITK and ctest is ran in the build directory, `itkGrayscaleImageSegmentationVolumeEstimatorTest1 ` fails with the following error:

![Screen Shot 2020-05-04 at 12 34 14 PM](https://user-images.githubusercontent.com/42974718/80996073-d7d07e00-8e04-11ea-8a98-7a1ce4b2cdf9.png)

Source of issue:
![Screen Shot 2020-05-04 at 12 49 50 PM](https://user-images.githubusercontent.com/42974718/80996867-27637980-8e06-11ea-9c71-049b809b7a29.png)

The function `FloatAlmostEqual` is comparing `1e-1` (0.1%) against the percent error in the volume estimation, with epsilon = `1e-6`. If we are asserting the percent error is less than .1%, would we want to compare the percent error against 0.0%, with epsilon = `1e-1`? If not, would this be an error in the estimator?

**Comment by dzenanz** [comment]
You are right. I think the condition should be: `if (!itk::Math::FloatAlmostEqual(percentage, 0.0, 10, allowedVolumePercentageError))` or something similar.

**Comment by mseng10** [comment]
@dzenanz Perfect, thank you! I will have a PR in shortly addressing this and other failing tests.
